; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = zero

[env]
framework = arduino
; paths are relative to this directory
build_flags = -DPLATFORM_PLATFORMIO
    -D ASSETS=USE_FLASH
    -D USE_TRIG_TABLE=
    -I../common
    -I../../snippets
    -I../../../include
; paths are relative to the src directory
build_src_filter = 
    +<**/*.c>
    +<**/*.cpp>
    +<../../common/*.c> 
    +<../../assets/c_array_assets/*.c> 
    +<../../../snippets/*.c>
    +<../../../snippets/maths/*.c>
    +<../../../../source/*.c>
    +<../../../../source/extensions/*.c>
    -<../../../../source/extensions/bt82x_patch.c>
    +<../../../../ports/eve_arch_platformio/*.cpp>
debug_init_break = loop

[env:zero]
platform = atmelsam
board = zero
build_flags =
    ${env.build_flags}
build_type = debug

[env:MM2040EV]
platform = raspberrypi
board = pico
; SPI and GPIO pins changed to match Bridgetek IDM2040-7A/MM2040EV boards.
build_flags =
    ${env.build_flags}
    -D PIN_REDEFINE=
    -D PIN_SPICLOCK=2
    -D PIN_DATAOUT=3
    -D PIN_DATAIN=4
    -D PIN_CHIPSELECT=5
    -D PIN_POWERDOWN=7
    -D PIN_INTERRUPT=6
upload_protocol = picotool
upload_port = D:
build_type = debug

[env:esp32thing]
platform = espressif32
board = esp32thing
build_flags =
    ${env.build_flags}
    -D PIN_REDEFINE=
    -D PIN_SPICLOCK=18
    -D PIN_DATAOUT=23
    -D PIN_DATAIN=19
    -D PIN_CHIPSELECT=22
    -D PIN_POWERDOWN=15
    -D PIN_INTERRUPT=2
build_type = debug

