/**
 @file EVE_MCU_STM32CUBE.c
*/
/*
* ============================================================================
* (C) Copyright Bridgetek Pte Ltd
* ============================================================================
*
* This source code ("the Software") is provided by Bridgetek Pte Ltd
* ("Bridgetek") subject to the licence terms set out
* https://brtchip.com/wp-content/uploads/2021/11/BRT_Software_License_Agreement.pdf ("the Licence Terms").
* You must read the Licence Terms before downloading or using the Software.
* By installing or using the Software you agree to the Licence Terms. If you
* do not agree to the Licence Terms then do not download or use the Software.
*
* Without prejudice to the Licence Terms, here is a summary of some of the key
* terms of the Licence Terms (and in the event of any conflict between this
* summary and the Licence Terms then the text of the Licence Terms will
* prevail).
*
* The Software is provided "as is".
* There are no warranties (or similar) in relation to the quality of the
* Software. You use it at your own risk.
* The Software should not be used in, or for, any medical device, system or
* appliance. There are exclusions of Bridgetek liability for certain types of loss
* such as: special loss or damage; incidental loss or damage; indirect or
* consequential loss or damage; loss of income; loss of business; loss of
* profits; loss of revenue; loss of contracts; business interruption; loss of
* the use of money or anticipated savings; loss of information; loss of
* opportunity; loss of goodwill or reputation; and/or loss of, damage to or
* corruption of data.
* There is a monetary cap on Bridgetek's liability.
* The Software may have subsequently been amended by another user and then
* distributed by that other user ("Adapted Software").  If so that user may
* have additional licence terms that apply to those amendments. However, Bridgetek
* has no liability in relation to those amendments.
* ============================================================================
*/

#if defined(PLATFORM_STM32_CUBE)

/* EVE MCU HEADER */

/* Header for STM32 (generated by STMCubeMX) */
#include <main.h>

/* SPI1 Enabled in STM32CubeMX for the STM32 */
#if defined(HAL_SPI_MODULE_ENABLED) && !defined(HAL_QSPI_MODULE_ENABLED)
#pragma message ("STM32Cube Single Channel SPI1 controller enabled")

/* EVE MCU HEADER END */

#include <stdint.h> // for Uint8/16/32 and Int8/16/32 data types

#include <EVE.h>
#include <MCU.h>

/* EVE MCU */

/* SPI handler declaration */
extern SPI_HandleTypeDef hspi1;

void MCU_Init(void)
{
    /* Set the SPI speed to a safe minimum. It must be
     * under 11 MHz but 1 MHz is very safe.
     * Use the "safe" prescaler to get a safe clock for SPI
     * during initialisation.
     */
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
    {
        Error_Handler();
    }
}

void MCU_Deinit(void)
{
    HAL_SPI_DeInit(&hspi1);
}

void MCU_Setup(void)
{
    /* Increase SPI speed after initialisation is complete.
     * See the notes for MCU_SPI_TIMEOUT in the MCU.h file.
     * This will set the SPI to maximum speed configured
     * in STM32CubeMX.
     * This can be a maximum of 60 MHz for BT820, or 30 MHz
     * on FT81x, BT88x, BT81x. */
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
    {
        Error_Handler();
    }
}

/* EVE_CS__GPIO_Port and EVE_CS__Pin are defined by STM32CubMX.
 * The "User Label" for the CS pin is set to "EVE CS#" in the
 * GPIO Mode and Configuration section.
 */
inline void MCU_CSlow(void)
{
    // CS# line low
    HAL_GPIO_WritePin(EVE_CS__GPIO_Port, EVE_CS__Pin, GPIO_PIN_RESET);
    // Perform a very short delay
    __NOP();
}

inline void MCU_CShigh(void)
{
    // CS# line high
    HAL_GPIO_WritePin(EVE_CS__GPIO_Port, EVE_CS__Pin, GPIO_PIN_SET);
    // Perform a very short delay
    __NOP();
}

uint8_t MCU_SPIReadWrite8(uint8_t DataToWrite)
{
    uint8_t DataRead;
    uint8_t TxBuffer;
    
    TxBuffer = DataToWrite;

#if 1
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 1, HAL_MAX_DELAY);
#else
    // Note that this call to the STM32 HAL returns a status value which can be checked 
    // as shown below in order to make the application more robust
    switch(HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)TxBuffer, (uint8_t *)DataRead, 1, HAL_MAX_DELAY))
    {
    case HAL_OK:
      /* Communication is completed */
    case HAL_TIMEOUT:
      /* A Timeout Occur */
      /* Call Timeout Handler */
      Timeout_Error_Handler();
      break;
      /* An Error Occur */
    case HAL_ERROR:
      /* Call Timeout Handler */
      Error_Handler();
      break;
    default:
      break;
  }
#endif
       
    return DataRead;
}

uint16_t MCU_SPIReadWrite16(uint16_t DataToWrite)
{
    uint16_t DataRead;
    uint16_t TxBuffer = DataToWrite;

    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 2, HAL_MAX_DELAY);

    return MCU_le16toh(DataRead);
}

uint32_t MCU_SPIReadWrite24(uint32_t DataToWrite)
{
    uint32_t DataRead;
    uint32_t TxBuffer = DataToWrite;
    
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 3, HAL_MAX_DELAY);

    return MCU_le32toh(DataRead);
}

uint32_t MCU_SPIReadWrite32(uint32_t DataToWrite)
{
    uint32_t DataRead;
    uint32_t TxBuffer = DataToWrite;

    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 4, HAL_MAX_DELAY);

    return MCU_le32toh(DataRead);
}

uint8_t MCU_SPIRead8(void)
{
    uint8_t DataRead = 0;

    DataRead = MCU_SPIReadWrite8(0);
    
    return DataRead;
}

void MCU_SPIWrite8(uint8_t DataToWrite)
{
    MCU_SPIReadWrite8(DataToWrite);
}

uint16_t MCU_SPIRead16(void)
{
    uint16_t DataRead = 0;

    DataRead = MCU_SPIReadWrite16(0);

    return MCU_le16toh(DataRead);
}

void MCU_SPIWrite16(uint16_t DataToWrite)
{
    MCU_SPIReadWrite16(DataToWrite);
}

uint32_t MCU_SPIRead24(void)
{
    uint32_t DataRead = 0;

    DataRead = MCU_SPIReadWrite24(0);

    return MCU_le32toh(DataRead);
}

void MCU_SPIWrite24(uint32_t DataToWrite)
{
    MCU_SPIReadWrite24(DataToWrite);
}

uint32_t MCU_SPIRead32(void)
{
    uint32_t DataRead = 0;

    DataRead = MCU_SPIReadWrite32(0);

    return MCU_le32toh(DataRead);
}

void MCU_SPIWrite32(uint32_t DataToWrite)
{
    MCU_SPIReadWrite32(DataToWrite);
}

void MCU_SPIWrite(const uint8_t *DataToWrite, uint32_t length)
{
    uint32_t DataPointer = 0;
    DataPointer = 0;

    while(DataPointer < length)
    {
        // Send data byte-by-byte from array
        MCU_SPIWrite8(DataToWrite[DataPointer]);
        DataPointer += sizeof(uint8_t);
    }
}

void MCU_SPIRead(uint8_t *DataToRead, uint32_t length)
{
    uint16_t DataPointer = 0;
    DataPointer = 0;

    while(DataPointer < length)
    {
        // Send data byte-by-byte from array
        DataToRead[DataPointer] = MCU_SPIRead8();
        DataPointer += sizeof(uint8_t);
    }
}

/* EVE MCU END */

#endif /* defined(HAL_SPI_MODULE_ENABLED) && !defined(HAL_QSPI_MODULE_ENABLED) */

#endif /* defined (PLATFORM_STM32_CUBE) */
