/**
 @file EVE_MCU_STM32CUBE.c
*/
/*
* ============================================================================
* (C) Copyright Bridgetek Pte Ltd
* ============================================================================
*
* This source code ("the Software") is provided by Bridgetek Pte Ltd
* ("Bridgetek") subject to the licence terms set out
* https://brtchip.com/wp-content/uploads/2021/11/BRT_Software_License_Agreement.pdf ("the Licence Terms").
* You must read the Licence Terms before downloading or using the Software.
* By installing or using the Software you agree to the Licence Terms. If you
* do not agree to the Licence Terms then do not download or use the Software.
*
* Without prejudice to the Licence Terms, here is a summary of some of the key
* terms of the Licence Terms (and in the event of any conflict between this
* summary and the Licence Terms then the text of the Licence Terms will
* prevail).
*
* The Software is provided "as is".
* There are no warranties (or similar) in relation to the quality of the
* Software. You use it at your own risk.
* The Software should not be used in, or for, any medical device, system or
* appliance. There are exclusions of Bridgetek liability for certain types of loss
* such as: special loss or damage; incidental loss or damage; indirect or
* consequential loss or damage; loss of income; loss of business; loss of
* profits; loss of revenue; loss of contracts; business interruption; loss of
* the use of money or anticipated savings; loss of information; loss of
* opportunity; loss of goodwill or reputation; and/or loss of, damage to or
* corruption of data.
* There is a monetary cap on Bridgetek's liability.
* The Software may have subsequently been amended by another user and then
* distributed by that other user ("Adapted Software").  If so that user may
* have additional licence terms that apply to those amendments. However, Bridgetek
* has no liability in relation to those amendments.
* ============================================================================
*/

#if defined(PLATFORM_STM32_CUBE)

#pragma message "Compiling " __FILE__ " for ST STM32_CUBE"

/* EVE MCU HEADER */

#define bswap16(x) (((x) >> 8) | ((x) << 8))
#define bswap32(x) (((x) >> 24) | (((x) & 0x00FF0000) >> 8) \
                  | (((x) & 0x0000FF00) << 8) | ((x) << 24))

/* Header for STM32 (generated by STMCubeMX) */
#include <main.h>

/* EVE MCU HEADER END */

#include <string.h>
#include <stdint.h> // For Uint8/16/32 and Int8/16/32 data types
#include <sys/endian.h>

#include <EVE.h>
#include <MCU.h>

/* EVE MCU */

void MCU_Delay_20ms(void)
{
    HAL_Delay(20);
}

void MCU_Delay_500ms(void)
{
    uint8_t dly = 0;

    for(dly =0; dly < 100; dly++)
    {
        HAL_Delay(20);
    }
}

/* EVE_PD__Pin and EVE_PD__GPIO_Port are defined by STM32CubMX.
 * The "User Label" for the PD pin is set to "EVE PD#" in the
 * GPIO Mode and Configuration section.
 */

inline void MCU_PDlow(void)
{
    // PD# line low
    HAL_GPIO_WritePin(EVE_PD__GPIO_Port, EVE_PD__Pin, GPIO_PIN_RESET);
}

inline void MCU_PDhigh(void)
{
    // PD# line high
    HAL_GPIO_WritePin(EVE_PD__GPIO_Port, EVE_PD__Pin, GPIO_PIN_SET);
}

uint16_t MCU_htobe16 (uint16_t h)
{
    return htobe16(h);
}

uint32_t MCU_htobe32 (uint32_t h)
{
    return htobe32(h);
}

uint16_t MCU_htole16 (uint16_t h)
{
    return htole16(h);
}

uint32_t MCU_htole32 (uint32_t h)
{
    return htole32(h);
}

uint16_t MCU_be16toh (uint16_t h)
{
    return be16toh(h);
}

uint32_t MCU_be32toh (uint32_t h)
{
    return be32toh(h);
}

uint16_t MCU_le16toh (uint16_t h)
{
    return le16toh(h);
}

uint32_t MCU_le32toh (uint32_t h)
{
    return le32toh(h);
}

/* EVE MCU END */

#endif /* defined (PLATFORM_STM32_CUBE) */
