# Typically run with "python flashmap.py flash-820-default.map ../common/eve_assetload_flash.c"
#
import sys
import os
import re
import argparse

parser = argparse.ArgumentParser(description="Flash Map Updater for EVE", 
                                 epilog="This program takes the flash image input file names from the flash map file. " \
                                 "It will update the values immediately after the C-comments starting \"offset\" and \"size\" " \
                                 "with a matching file name. " \
                                 "It must be run to update the C file that informs the program where the various assets are " \
                                 "located in the flash image. "
                                 )
parser.add_argument("mapfile", help="map file for flash image (generated by EAB)")
parser.add_argument("cfile", help="C file to update with address and size of flash contents")
(args, rem) = parser.parse_known_args()

print(f"Setting map offsets and sizes from \"{args.mapfile}\" to \"{args.cfile}\"")
with open(args.mapfile, "r") as mapf:
    maplines = [line.rstrip() for line in mapf]
    maps = []
    for line in maplines:
        maps.append([col.strip() for col in line.split(":")])

    with open(args.cfile, "r") as cf:
        clines = [line for line in cf]

    # Pattern for finding C-comment starting with (offset|size)
    # containing a flash source image file name followed by a
    # decimal value (that will be modified with updated values)
    pattern = re.compile(r"/\* (\w+) (.+) \*/\s*[0-9]+s*")

    with open(args.cfile, "w") as cf:
        # Parse the C file and find /* (offset|size) <file> */
        for cline in clines:
            m = pattern.search(cline)
            if m:
                # Find type and filename
                type = m.group(1)
                fname = m.group(2)
                if type and fname:
                    for map in maps:
                        if fname == map[0]:
                            if type == "offset": val = map[1]
                            if type == "size": val = map[2]
                            cline = cline[:m.start()] + f"/* {type} {fname} */ {val} " + cline[m.end():]
            cf.write(cline)
