name: Test API

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - 'main'
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/api_test.yml'
      # Trigger script on push to test directory
      - 'test/**'
      # Trigger script on push to API
      - 'include/**'
      - 'source/**'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        eve: [ 
          {EVE_DISPLAY_RES: EVE_QVGA, EVE_DEVICE: EVE_FT800, EVE_PANEL: EVE_NO_PANEL , EVE_MODULE: EVE_NO_MODULE }, 
          {EVE_DISPLAY_RES: EVE_NO_RES, EVE_DEVICE: EVE_FT813, EVE_PANEL: EVE_DP_0431_11A , EVE_MODULE: EVE_NO_MODULE }, 
          {EVE_DISPLAY_RES: EVE_WVGA, EVE_DEVICE: EVE_BT815, EVE_PANEL: EVE_NO_PANEL , EVE_MODULE: EVE_NO_MODULE }, 
          {EVE_DISPLAY_RES: EVE_NO_RES, EVE_DEVICE: EVE_NO_DEVICE, EVE_PANEL: EVE_NO_PANEL , EVE_MODULE: EVE_IDM20407A }, 
          {EVE_DISPLAY_RES: EVE_WUXGA, EVE_DEVICE: EVE_BT820, EVE_PANEL: EVE_NO_PANEL , EVE_MODULE: EVE_NO_MODULE }, 
        ]
    
    # Set the name of the job to include the important information
    name: test api - ${{ matrix.eve.EVE_DEVICE }} ${{ matrix.eve.EVE_MODULE }} ${{ matrix.eve.EVE_PANEL }} ${{ matrix.eve.EVE_DISPLAY_RES }}

    steps:
    - uses: actions/checkout@v6

    # Test using matrix
    - name: Configure CMake
      run: cmake -B build -S . -G Ninja -DEVE_MODULE=${{ matrix.eve.EVE_MODULE }} -DEVE_PANEL=${{ matrix.eve.EVE_PANEL }} -DEVE_DEVICE=${{ matrix.eve.EVE_DEVICE }} -DEVE_DISPLAY_RES=${{ matrix.eve.EVE_DISPLAY_RES }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/test/boottester

    - name: Build
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/boottester

    - name: Run test 
      run: ${{github.workspace}}/test/boottester/build/boottester
