name: Test API

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - 'main'
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/api_test.yml'
      # Trigger script on push to test directory
      - 'test/**'
      # Trigger script on push to API
      - 'include/**'
      - 'source/**'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        eve: [ 
          {name: "FT800/QVGA", config: "-DEVE_DISPLAY_RES=EVE_QVGA -DEVE_DEVICE=EVE_FT800" }, 
          {name: "FT813/WQVGA", config: "-DEVE_PANEL=EVE_DP_0431_11A -DEVE_DEVICE=EVE_FT813" }, 
          {name: "BT815/WVGA", config: "-DEVE_DISPLAY_RES=EVE_WVGA -DEVE_DEVICE=EVE_BT815" }, 
          {name: "BT817(IDM2040-7A)", config: "-DEVE_MODULE=IDM20407A" }, 
          {name: "BT820/WUXGA", config: "-DEVE_DISPLAY_RES=EVE_WUXGA -DEVE_DEVICE=EVE_BT820" }, 
        ]
    
    # Set the name of the job to include the important information
    name: test api - ${{ matrix.eve.name }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'false'

    # Test using matrix
    - name: Configure CMake
      run: cmake -B build -S . -G Ninja ${{ matrix.eve.config }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/test/boottester

    - name: Build
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/boottester

    - name: Run test 
      run: ${{github.workspace}}/test/boottester/build/boottester
