# This test is disabled as FTDI have implemented a cloudflare filter for these files.
name: Build Simple Example for Linux 

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - main
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/build_linux.yml'
      # Trigger script on push to simple example
      - 'examples/simple/**'
      # Trigger on API change
      - 'include/**'
      - 'source/**'
      - 'ports/**'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        example: [
          {dir: raspberry_pi,   compiler: arm,  library: rpi},
          {dir: pico,           compiler: arm,  library: pico},
          {dir: STM32CUBE_CMake_MiniSTM32H7xx, compiler: arm, library: none },
        ]
        eve: [ 
          {DISPLAY_RES: QVGA, FT8XX_TYPE: FT800, PANEL_TYPE: NO_PANEL , MODULE_TYPE: NO_MODULE }, 
          {DISPLAY_RES: NO_RES, FT8XX_TYPE: FT813, PANEL_TYPE: DP_0431_11A , MODULE_TYPE: NO_MODULE }, 
          {DISPLAY_RES: WVGA, FT8XX_TYPE: BT815, PANEL_TYPE: NO_PANEL , MODULE_TYPE: NO_MODULE }, 
          {DISPLAY_RES: NO_RES, FT8XX_TYPE: NO_FT8XX, PANEL_TYPE: NO_PANEL , MODULE_TYPE: IDM20407A }, 
          {DISPLAY_RES: WUXGA, FT8XX_TYPE: BT820, PANEL_TYPE: NO_PANEL , MODULE_TYPE: NO_MODULE }, 
        ]
    
    # Set the name of the job to include the important information
    name: build ${{ matrix.example.dir }} - ${{ matrix.eve.FT8XX_TYPE }} ${{ matrix.eve.MODULE_TYPE }} ${{ matrix.eve.PANEL_TYPE }} ${{ matrix.eve.DISPLAY_RES }}

    steps:
    - uses: actions/checkout@v6

    # Use a cached version of gcc for arm from https://github.com/carlosperate (thanks!)
    - name: Setup gcc-arm-none-eabi environment
      if: ${{ matrix.example.compiler == 'arm' }}
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      # Equivalent to the following line but uses caches for speed:
      # run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi

    - name: Setup Linux GPIO library
      if: ${{ matrix.example.library == 'rpi' }}
      run: |
        sudo apt-get update && sudo apt-get install libgpiod-dev
  
    - name: Get SDK and add PICO_SDK_PATH
      if: ${{ matrix.example.library == 'pico' }}
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git && echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV
      # Do not need btstack, lwip, mbedtls, tinyusb or cyw43 - just the SDK
      # ls && cd pico-sdk && git submodule update --init && cd ..
     
    # Test using matrix
    - name: Configure CMake
      run: cmake -B build -S . -G Ninja -DMODULE_TYPE=${{ matrix.eve.MODULE_TYPE }} -DPANEL_TYPE=${{ matrix.eve.PANEL_TYPE }} -DFT8XX_TYPE=${{ matrix.eve.FT8XX_TYPE }} -DDISPLAY_RES=${{ matrix.eve.DISPLAY_RES }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/${{ matrix.example.dir }}

    - name: Build
      run: cmake --build build
      working-directory: ${{github.workspace}}/examples/simple/${{ matrix.example.dir }}

