name: Build Simple Example for Linux 

on:
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - main
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/build_linux.yml'
      # Trigger script on push to raspberry_pi simple example
      - 'examples/simple/common'
      - 'examples/simple/libft4222'
      - 'examples/simple/libmpsse'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get libFT4222 library
      run: |
          curl --insecure -O "https://ftdichip.com/wp-content/uploads/2025/04/libft4222-linux-1.4.4.232.zip"
          unzip libft4222-linux-1.4.4.232.zip
          tar -xvf libft4222-linux-1.4.4.232.tgz
          sudo ./install4222.sh

    - name: Get libMPSSE-SPI library
      run: |
          curl --insecure -O "https://ftdichip.com/wp-content/uploads/2025/08/libmpsse-x86_64-1.0.8.tgz"
          tar xfvz libmpsse-x86_64-1.0.8.tgz
          cd release
          chmod +x install_libmpsse.sh
          ./install_libmpsse.sh
      
    # Test BT820 (EVE API 5)
    - name: Configure CMake for libFT4222 Linux on BT820 with WUXGA panel (DP_1012_01A)
      run: cmake -B build820WUXGA -S . -DDISPLAY_RES=WUXGA -DFT8XX_TYPE=BT820 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    - name: Build for libFT4222 Linux on BT820 with WUXGA panel (DP_1012_01A)
      run: cmake --build build820WUXGA
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    # Test BT816 (EVE API 3)
    - name: Configure CMake for libFT4222 Linux on IDM20407A module (BT816 with WVGA resolution DP_0701_11A panel)
      run: cmake -B buildIDM20407A -S . -DMODULE_TYPE=IDM20407A -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    - name: Build for libFT4222 Linux on IDM20407A module on (BT816 with WVGA resolution DP_0701_11A panel)
      run: cmake --build buildIDM20407A
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    # Test FT813 (EVE API 2 SUB API 1)
    - name: Configure CMake for libFT4222 Linux on FT813 with DP_0501_01A panel (WVGA)
      run: cmake -B build813WVGA -S . -DFT8XX_TYPE=FT813 -DPANEL_TYPE=DP_0501_01A -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    - name: Build for libFT4222 Linux on IDM20407A module on FT813 with DP_0501_01A panel (WVGA)
      run: cmake --build build813WVGA
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    # Test FT800 (EVE API 1)
    - name: Configure CMake for libFT4222 Linux on VM800C43A (FT800 with WQVGA resolution DP-0431-11A panel)
      run: cmake -B build800C43A -S . -DFT8XX_TYPE=FT813 -DPANEL_TYPE=DP_0501_01A -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    - name: Build for libFT4222 Linux on VM800C43A (FT800 with WQVGA resolution DP-0431-11A panel)
      run: cmake --build build800C43A
      working-directory: ${{github.workspace}}/examples/simple/libft4222

    # Test BT820 (EVE API 5)
    - name: Configure CMake for libMPSSE-SPI Linux on BT820 with WUXGA panel (DP_1012_01A)
      run: cmake -B build820WUXGA -S . -DDISPLAY_RES=WUXGA -DFT8XX_TYPE=BT820 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/examples/simple/libmpsse

    - name: Build for libFT4222 Linux on BT820 with WUXGA panel (DP_1012_01A)
      run: cmake --build build820WUXGA
      working-directory: ${{github.workspace}}/examples/simple/libmpsse

