name: Build Simple Example for Arduino

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - 'main'
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/build_arduino.yml'
      # Trigger script on push to simple arduino example
      - 'examples/simple/arduino/**'
      # Trigger script on push to API
      - 'include/**'
      - 'source/**'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        example: [
          {fqbn: arduino:avr:uno, platform: arduino:avr},
          {fqbn: arduino:samd:adafruit_circuitplayground_m0, platform: arduino:samd},
          {fqbn: esp32:esp32:esp32, platform: esp32:esp32},
        ]
        eve: [ 
          {name: "FT800/QVGA", config: "-DEVE_DISPLAY_RES=EVE_QVGA -DEVE_DEVICE=EVE_FT800" }, 
          {name: "FT813/WQVGA", config: "-DEVE_PANEL=EVE_DP_0431_11A -DEVE_DEVICE=EVE_FT813" }, 
          {name: "BT815/WVGA", config: "-DEVE_DISPLAY_RES=EVE_WVGA -DEVE_DEVICE=EVE_BT815" }, 
          {name: "BT817(IDM2040-7A)", config: "-DEVE_MODULE=IDM20407A" }, 
          {name: "BT820/WUXGA", config: "-DEVE_DISPLAY_RES=EVE_WUXGA -DEVE_DEVICE=EVE_BT820" }, 
        ]
    
    # Set the name of the job to include the important information
    name: build Arduino ${{ matrix.example.platform }} - ${{ matrix.eve.name }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'false'

    - name: Build sketch source
      run: python sketchbuild.py
      working-directory: ${{github.workspace}}/examples/simple/arduino

    - name: 
      uses: arduino/compile-sketches@v1
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.example.fqbn }}
          verbose: false
          libraries: |
            []
          platforms: |
            - name: ${{ matrix.example.platform }}
          sketch-paths: |
            - examples/simple/arduino/simple_arduino
          cli-compile-flags: |
            - --build-property
            - compiler.cpp.extra_flags=${{ matrix.eve.config }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

