name: Test Examples

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      # Trigger script on push to 'development' branch
      #- development
      # Trigger script on push to 'main' branch
      - 'main'
    paths:
      # Trigger if this workflow file changes
      - '.github/workflows/example_test.yml'
      # Trigger script on push to test directory
      - 'test/**'
      # Trigger script on push to API
      - 'include/**'
      - 'source/**'
      - 'examples/**'
  # Add "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        eve: [ 
          {EXAMPLE: simple, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: b2tf, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: cruise, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: datavisualiser, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: flightdeck, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: fontmagic, ASSETS: 0, EVE1: false, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: gyminterval, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: medinfo, ASSETS: USE_C_ARRAYS, EVE1: false, EVE2: false, EVE3: FULLHD, EVE4: FULLHD, EVE5: WUXGA }, 
          {EXAMPLE: racecar, ASSETS: USE_C_ARRAYS, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: submarine, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
          {EXAMPLE: touchscreentest, ASSETS: 0, EVE1: QVGA, EVE2: WQVGA, EVE3: WVGA, EVE4: WXGA, EVE5: WUXGA }, 
        ]
    
    # Set the name of the job to include the important information
    name: test example - ${{ matrix.eve.EXAMPLE }}

    steps:
    - uses: actions/checkout@v6

    # Test using matrix
    - name: Configure CMake EVE5
      if: ${{ matrix.eve.EVE5 != false }}
      run: cmake -B build -S . -G Ninja -DFT8XX_TYPE=BT820 -DDISPLAY_RES=${{ matrix.eve.EVE5 }} -DEXAMPLE=${{ matrix.eve.EXAMPLE }} -DASSETS=${{ matrix.eve.ASSETS }}
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Build EVE5
      if: ${{ matrix.eve.EVE5 != false }}
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Configure CMake EVE4
      if: ${{ matrix.eve.EVE4 != false }}
      run: cmake -B build -S . -G Ninja -DFT8XX_TYPE=BT818 -DDISPLAY_RES=${{ matrix.eve.EVE4 }} -DEXAMPLE=${{ matrix.eve.EXAMPLE }} -DASSETS=${{ matrix.eve.ASSETS }}
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Build EVE4
      if: ${{ matrix.eve.EVE4 != false }}
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Configure CMake EVE3
      if: ${{ matrix.eve.EVE3 != false }}
      run: cmake -B build -S . -G Ninja -DFT8XX_TYPE=BT815 -DDISPLAY_RES=${{ matrix.eve.EVE3 }} -DEXAMPLE=${{ matrix.eve.EXAMPLE }} -DASSETS=${{ matrix.eve.ASSETS }}
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Build EVE3
      if: ${{ matrix.eve.EVE3 != false }}
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Configure CMake EVE2
      if: ${{ matrix.eve.EVE2 != false }}
      run: cmake -B build -S . -G Ninja -DFT8XX_TYPE=FT812 -DDISPLAY_RES=${{ matrix.eve.EVE2 }} -DEXAMPLE=${{ matrix.eve.EXAMPLE }} -DASSETS=${{ matrix.eve.ASSETS }}
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Build EVE2
      if: ${{ matrix.eve.EVE2 != false }}
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Configure CMake EVE1
      if: ${{ matrix.eve.EVE1 != false }}
      run: cmake -B build -S . -G Ninja -DFT8XX_TYPE=FT800 -DDISPLAY_RES=${{ matrix.eve.EVE1 }} -DEXAMPLE=${{ matrix.eve.EXAMPLE }} -DASSETS=${{ matrix.eve.ASSETS }}
      working-directory: ${{github.workspace}}/test/exampletester

    - name: Build EVE1
      if: ${{ matrix.eve.EVE1 != false }}
      run: cmake --build build
      working-directory: ${{github.workspace}}/test/exampletester

    # Do not run the executable as it may not support the operations - we are testing compilation only
    #- name: Run test 
    #  run: ${{github.workspace}}/test/exampletester/build/exampletester
